Repository COSC481W-2024Winter/Fictionary-Backend, pull requests merged in 2024-03, with the labels that each got.

#17 backend: added event-listener 'updateScores' to the server socket
  _tests_/index.test.js
  index.js
  package-lock.json
  package.json
Labels: Scope: Backend, Sprint 2, Feature, Game logic

#18 Add: Request Handling logic (category logic/fetching)
  .gitignore
  index.js
  package-lock.json
  package.json
Labels: Sprint 2, Game logic, database

#20 Fix: dotenv variables being undefined
  index.js
  package-lock.json
  package.json
Labels: bug, Scope: Backend, Sprint 3, database
