Repository COSC481W-2024Winter/Fictionary-Backend, pull requests merged in 2024-04, with the labels that each got.

#22 add: room ID validation
  index.js
Labels: enhancement, Scope: Backend, Sprint 3, database

#25 fix: players continuing
  index.js
Labels: bug, enhancement, Scope: Backend, Sprint 3, Game logic

#30 backend: add a variable 'roomGuesses' with listeners 'submitGuess' and 'changeGuesses' to communicate with the frontend
  index.js
Labels: Scope: Backend, Sprint 3, Feature, Game logic

#27 Feature: Added Chat log functionality
  index.js
Labels: Scope: Backend, Sprint 3, Feature

#31 add: display drawings on multiple pages
  index.js
Labels: enhancement, Scope: Backend, Sprint 3, Game logic

#32 Commented (most) unnecessary console logs
  index.js
Labels: enhancement, Scope: Backend, Sprint 3
